#!/bin/bash

_bus()
{
    busctl --user $@ org.gnome.Terminal
}

_sid()
{
    _bus tree --list|sed -n 's|.*screen/||p'|tail -1
}

_name()
{
    _bus status|sed -n 's/UniqueName=//p'
}

_activate_window()
{
    busctl --user call org.gnome.Shell \
      /de/lucaswerkmeister/ActivateWindowByTitle \
      de.lucaswerkmeister.ActivateWindowByTitle \
      activateByWmClass s "$1"
}

_newtab()
{
    set -u
    local bin=gnome-terminal sid=$(_sid)
    if [[ $sid ]]; then
        local scr=/org/gnome/Terminal/screen/$sid
        local env="GNOME_TERMINAL_SERVICE=$(_name) GNOME_TERMINAL_SCREEN=$scr"
        bin="env $env $bin"
    fi
    $bin --tab "$@"
    if [[ $? == 0 ]]; then
        _activate_window $bin-server
    fi
}

_newtab "$@"
